name: event_bus_basics
description: A Dart package for logging events once and writing them to multiple services.
version: 1.0.0
repository: https://github.com/larryaasen/event_bus_basics

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:

  equatable: '>=1.0.0 <4.0.0'
  logger: '>=1.0.0 <3.0.0'
  stack_trace: '>=1.10.0 <3.0.0'

dev_dependencies:
  lints: '>=2.0.0 <4.0.0'
  test: '>=1.16.0 <3.0.0'
