name: event_bus_basics
description: A Dart package for logging events once and writing them to multiple services.
version: 1.0.0
repository: https://github.com/larryaasen/event_bus_basics

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:

  equatable: ^2.0.5
  logger: ^1.4.0
  stack_trace: ^1.11.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
