name: main

on:
  pull_request:
    types: [review_requested, opened, synchronize]
    paths-ignore:
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'

  push:
    branches:
      - '*'
    paths-ignore:
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        sdk: [2.17.0, 3.0.0, stable, beta, dev]

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Get packages
        run: dart pub get

      - name: Analyze
        run: dart analyze
      
      - name: Run unit tests
        run: dart test --coverage=coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
          env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  